version: '2'
services:
    ribbon_cache-app:
        image: ribbon_cache
        external_links:
            - ribbon_cache-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - ribbon_cache-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ribbon_cache
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    ribbon_cache-postgresql:
        extends:
            file: postgresql.yml
            service: ribbon_cache-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: ribbon_cache-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
