version: '2'
services:
    ribbon_cache-cassandra:
        container_name: ribbon_cache-cassandra
        image: cassandra:2.2.5
        # volumes:
        #     - ~/volumes/jhipster/ribbon_cache/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    ribbon_cache-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: ribbon_cache-cassandra-migration
        links:
            - ribbon_cache-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
